  DROP TABLE IF EXISTS EXCHANGE;
  
CREATE TABLE EXCHANGE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  currency_from VARCHAR(250) NOT NULL,
  currency_to VARCHAR(250) NOT NULL,
  conversion_val DOUBLE NOT NULL
  );